### ISSUE TITLE
up arrow at bottom of page obscures SM icons

### ISSUE THREAD

**Issue by e4c5** [Strawberry-pumpkin/wysc-website#4]
![image](https://github.com/Strawberry-pumpkin/wysc-website/assets/1635446/22bdffd5-0468-4e60-880f-1e9881fe4e2b)

**Comment by Strawberry-pumpkin** [comment]
uncle could you specify on the issue here, i can't see the arrow in the screenshot you uploaded ( i'm assuming that isnt the issue)

**Comment by e4c5** [comment]
I misunderstood the layout. There is a apparently a dark footer at the bottom of the page that creates the impression that the up arrow layer is covering the social media icons.
Nevertheless the visibility of that needs to be improved

**Comment by Strawberry-pumpkin** [comment]
yes uncle i noted that, changed the footer colour to a lighter theme, 
![image_2024-05-24_094601667](https://github.com/Strawberry-pumpkin/wysc-website/assets/103160608/c3bd5d99-d54f-4ab3-80f4-30e769583736)
